Invitation/urls.py
from django.conf import settings
from django.conf.urls.static import static

from os import name
from django.contrib import admin
from django.urls import path
from django.contrib.auth import views as auth_views
from django.urls.conf import include

from apps.core.views import frontpage,privacy, terms,plans,code
from apps.userprofile.views import accept_invitation

urlpatterns = [
    path('', frontpage, name='frontpage'),
    path('terms/', terms, name='terms'),
    path('privacy/', privacy, name='privacy'),
    path('plans/', plans, name='plans'),
    path('admin/', admin.site.urls),
    
    #
    #Dashboard
    
      path('myaccount/', include('apps.userprofile.urls')), 
      path('myaccount/teams/', include('apps.team.urls')), 
    #
    #Auth
    
    #path('sign/', include('apps.userprofile.urls')),
    path('signup/', code, name="signup"),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html' ), name="login"),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
  
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/team/urls.py
#import django

from django.conf.urls import url
from django.urls import path

from .views import add, team, edit,activate_team, invite
app_name = 'team'

urlpatterns = [
    path('add/', add, name='add'),
    path('edit/', edit, name='edit'),
    path('invite/', invite, name='invite'),
    path('activate_team/<int:team_id>', activate_team, name='activate_team'),
    path('<int:team_id>/', team, name='team'),
    
]

apps/userprofile/urls.py
from django.urls import path

#
#
from apps.core.views import register, reg

from apps.articles.views import add_article_page, admin_dashboard, delArtsAdmin, delete_cat, edit_article_admin, edit_article_page, deleteArticle

#admin url imports
from apps.articles.views import admin_dashboard, manage_articles, add_articles_admin, deleteArticleAdmin,manage_categories, add_cat, delete_cat, edit_cat, delArtsAdmin, edit_admin_prof

#accounts
from apps.articles.views import manage_account


from .views import myaccount,edit_profile, accept_invitation
urlpatterns = [
      path('', accept_invitation, name='accept_invitation'),
    path('edit_profile/', edit_profile, name='edit_profile'),
    path('reg/', reg, name='reg'),
    path('register/', register, name='register'),
    path('myaccount/', myaccount, name='myaccount'),
    
    
    #User article paths
    path('add_article/', add_article_page, name='add_article'),
    path('edit_article/<str:art_code>/', edit_article_page, name='edit_art'),
    path('delete_article/<str:art_code>/', deleteArticle, name='del_art'),
    
    #ADMIN URLS
    path('admin_dashboard/',admin_dashboard, name='admin_dashboard'), #for dashboard
    
    path('manage_articles/',manage_articles, name='manage_articles'), #to manage articles
    path('add_articles_admin/',add_articles_admin, name='add_articles_admin'), #add an article
    path('edit_article_admin/<str:art_code>/', edit_article_admin, name='edit_art_admin'), #edit an article
    path('edit_article_admin/<str:art_code>/', edit_article_admin, name='edit_art_admin'), #edit an article
    path('delete_article_admin/<str:art_code>/', deleteArticleAdmin, name='del_art_admin'), #delete an article
    path('delete_articles_admin/',delArtsAdmin, name='del_arts'), #add an article
    
    
    path('manage_categories/',manage_categories, name='manage_categories'), #manage categories
    path('add_category/', add_cat, name='add_cat'),
    path('add_category/<str:cat_name>/', add_cat, name='add_cat'),
    path('edit_category/', edit_cat, name='edit_cat'), #
    path('delete_category/<int:cat_id>/', delete_cat, name='del_cat'), #
    path('manage_account/', manage_account, name='manage_account'), #
    path('edit_prof/', edit_admin_prof, name='edit_prof'), #
    
    
]

apps/team/models.py
from Invitation.settings import DEFAULT_AUTO_FIELD
from django.db import models
from django.contrib.auth.models import User
from django.db.models.fields import CharField
# Create your models here.

class Team(models.Model):
    ACTIVE = 'active'
    DELETED = 'deleted'
    
    CHOICES_STATUS = {
        (ACTIVE, 'Active'),
        (DELETED, 'Deleted'),
    }
    
    #
    #
    title = models.CharField(max_length=255)
    members = models.ManyToManyField(User,related_name="teams")
    created_by = models.ForeignKey(User,related_name="created_teams", on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    status = models.CharField( max_length=10, choices=CHOICES_STATUS, default=ACTIVE)
    
    class Meta:
        ordering= ['title']
    
    def __str__(self):
        return self.title
    
class Invite(models.Model):
    #
    # Status
    INVITED = 'Invited'
    ACCEPTED = 'Accepted'

    CHOICES_STATUS = (
        (INVITED, 'Invited'),
        (ACCEPTED, 'Accepted')
    )
    team = models.ForeignKey(Team, related_name="invitations", on_delete=models.CASCADE)
    email= models.EmailField()
    code = models.CharField( max_length=20)
    status = models.CharField( max_length=20, choices=CHOICES_STATUS, default=INVITED)
    date_sent = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.email
    

apps/userprofile/models.py
from django.db import models
from django.contrib.auth.models import User

from django.templatetags.static import static


from apps.team.models import Team
from django.contrib.auth.models import User
# Create your models here.



class Userprofile(models.Model):
    user = models.OneToOneField(User, related_name= 'userprofile',  on_delete=models.CASCADE )
    #user = models.CharField( max_length=50)
    active_team_id = models.IntegerField(default=0)
    avatar = models.ImageField(upload_to='uploads/avatars/', blank=True, null=True)
    is_leader = models.BooleanField(default=False)
    
    def get_avatar(self):
        if self.avatar:
            return self.avatar.url 
        else:
          #'  return 'static/images/user.png'
            return static("images/user.png")
    
    def get_team_name(self):
        name = list(Team.objects.filter(id=self.active_team_id).values_list('title', flat=True).distinct())
        #print(name[0])
        return f'{name[0]}'
    
    def __str__(self):
      
        return f'{self.user.username } ({self.user.first_name} {self.user.last_name})'
    

apps/userprofile/views.py
from apps.articles.models import Articles
from django.core.mail.message import EmailMultiAlternatives
from django.http.response import HttpResponse
from apps.team.utilities import send_invitation_accepted
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required

# Create your views here.

from django.contrib.auth.models import User

from .models import Userprofile
from apps.team.models import Invite, Team


#views



@login_required
def myaccount(request):
    teams = request.user.teams.exclude(pk=request.user.userprofile.active_team_id)
    invitations = Invite.objects.filter(email=request.user.email, status=Invite.INVITED)
    articles = Articles.objects.all()
    
    if request.user.userprofile.is_leader:
       messages.info(request,'Welcome Admin!')
       #return render(request, 'userprofile/admin/account_index.html', {}) 
       return render(request, 'core/frontpage1.html', {}) 
    else:
    
        return render(request, 'userprofile/myaccount.html',{'teams' : teams, 'invitations':invitations, 'articles':articles})

@login_required
def edit_profile(request):
    
    if request.method == 'POST':
        request.user.first_name = request.POST.get('first_name', '')
        request.user.last_name = request.POST.get('last_name', '')
        request.user.email = request.POST.get('email', '')
        request.user.save()
        
        if request.FILES:
            avatar = request.FILES['avatar']
            userprofile = request.user.userprofile
            userprofile.avatar = avatar
            userprofile.save()
        
        messages.info(request, 'The changes were Saved!')    
        return redirect('myaccount')
    
    return render(request, 'userprofile/edit_profile.html')
    


def accept_invitation(request):
    if request.method=='POST':
        code = request.POST.get('code')
        email = request.POST.get('email')
      #  passs = request.POST.get('pass')
        
        print(email)
        print(code)
      #  print(passs)
        invitations = Invite.objects.filter(code=code, email=email)
        
        if invitations:
            
            invitation = invitations[0]
            invitation.status = Invite.ACCEPTED
            invitation.save()
            """
            team = invitation.team
            team.members.add(request.user)
            team.save()
            
            userprofile = request.user.userprofile  
            userprofile.active_team_id = team.id
            userprofile.save()  
            
            messages.info(request, 'Invitations Accepted')
            
            send_invitation_accepted(team, invitation)
            
            #return HttpResponse('<h1>OK</h1>')
            return redirect('team:team', team_id=team.id)
        """
            #return HttpResponse('<h1>OK</h1>')
            
            #'render(request, 'core/signup.html', {})
            return redirect('reg')
        else:
            messages.info(request, 'Invitation was not found')
    else:
        return render(request, 'userprofile/accept_invitation.html')

apps/userprofile/templates/userprofile/accept_invitation.html
{% extends 'core/base.html' %}

{% block title %}Accept invitation | {% endblock %}

{% block content %}
    <nav class="breadcrumb" aria-label="breadcrumbs">
        <ul>
            <li><a href="/">Home Page</a></li>
            <li><a href="{% url 'myaccount' %}">My account</a></li>
            <li class="is-active"><a href="{% url 'accept_invitation' %}" aria-current="page">Accept invitation</a></li>
        </ul>
    </nav>

    <div class="columns">
        <div class="column is-4">
            <h1 class="title">Accept invitation</h1>

            <form method="POST" action="{% url 'accept_invitation' %}">
                {% csrf_token %}
                
                <div class="field">
                    <label>Your Email</label>
                  
                    <label>E-mail</label>

                    <div class="control">
                        <input type="email" name="email" id="id_username" class="input">
                    </div>
                  
                   <label>Your Code (from e-mail)</label>
                    <div class="control">
                        <input type="text" name="code" id="id_code" class="input">
                    </div>
                </div>

                <div class="field">
                    <div class="control">
                        <button class="button is-success">Submit</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

apps/userprofile/templates/userprofile/edit_profile.html
{% extends 'core/base.html' %}

{% block title %}Edit profile | {% endblock %}

{% block content %}
    <nav class="breadcrumb" aria-label="breadcrumbs">
        <ul>
            <li><a href="/">Home Page</a></li>
            <li><a href="{% url 'myaccount' %}">My account</a></li>
            <li class="is-active"><a href="{% url 'edit_profile' %}" aria-current="page">Edit profile</a></li>
        </ul>
    </nav>

    <div class="columns">
        <div class="column is-4">
            <h1 class="title">Edit profile</h1>

            <form method="post" action="." enctype="multipart/form-data">
                {% csrf_token %}

                <div class="field">
                    <label>First name</label>

                    <div class="control">
                        <input type="text" name="first_name" id="first_name" class="input"{% if request.user.first_name %} value="{{ request.user.first_name }}"{% endif %}>
                    </div>
                </div>

                <div class="field">
                    <label>Last name</label>

                    <div class="control">
                        <input type="text" name="last_name" id="last_name" class="input"{% if request.user.last_name %} value="{{ request.user.last_name }}"{% endif %}>
                    </div>
                </div>

                <div class="field">
                    <label>E-mail</label>

                    <div class="control">
                        <input type="text" name="email" id="email" class="input"{% if request.user.email %} value="{{ request.user.email }}"{% endif %}>
                    </div>
                </div>
                
                 <div class="field">
                    <label>Avatar</label>

                    <figure class="image is-64x64">
                        <img src="{{ request.user.userprofile.get_avatar }}">
                    </figure>

                    <div class="control mt-2">
                        <input type="file" name="avatar" id="id_avatar" class="input">
                    </div>
                </div>

                <!--This GOES IN teams/views.py-->

                <div class="field">
                    <div class="control">
                        <button class="button is-success">Save changes</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

apps/userprofile/templates/userprofile/myaccount.html
{% extends 'core/base.html' %}

{% block title %}My Account | {% endblock %}

{% block content %}
<link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>

    <nav class="breadcrumb" arial-label="breadcrumbs">
        <ul>
            <li><a href="/">Home Page</a></li>
            <li class="is-active"><a href="{% url 'myaccount' %}" aria-current="page">My account</a></li>
        </ul>
    </nav>

<div class="columns">
    <div class="column is-6">
        <div class="media mb-4">
            <div class="media-left">
                <figure class="image is-64x64" >
                    <img src="{{user.userprofile.get_avatar}}">
                </figure>

            </div>

          <div class="media-content">
                    <p class="title is-3">{% firstof user.get_full_name user.username %}</p>
                    <p class="subtitle is-6">{{ user.email }}</p>
                </div>
        </div>
          <a href="{% url 'edit_profile' %}" class="button is-info">Edit Profile</a>
    <a href="{% url 'logout' %}" class="button is-danger">Log Out</a>
    </div>
</div>


    {% if invitations %}
    <div class="notification is-info">
        <h2 class="subtitle">You have pending invitations</h2>

        {% for invitation in invitations %}
            <a href="{% url 'accept_invitation' %}">{{ invitation.team.title }}</a>
        {% endfor %}
    </div>
    {% endif %}

            <!--<div class="columns">
        <div class="column is-12">
         <a href="{% url 'team:add' %}" class="button is-success">Add team</a>
        </div>-->
    </div>
    
    <a href="{% url 'add_article' %}" class="button is-link">
        <i class="fas fa-plus-square"></i> &nbsp 
     Add Article</a>

    <br>
    <div></div>



<div>
   
    <table class="table is-hoverable is-bordered is-fullwidth is-striped is-narrow">
    <thead>
        <tr>
            <th style="width: 300px;"><abbr title="Position">Article Code</abbr></th>
            <th style="width: 300px;">Article Title</th>
            <th style="width: 300px;">Article Category </th>
            <th style="width: 300px;">Article Summary</th>
            <th style="width: 300px;">Article Volume</th>
            <th style="width: 300px;">Article Publication Date</th>
            <th style="width: 300px;">Published By</th>
            <th style="width: 300px;">Edit Article</th>
            <th style="width: 300px;">More</th>
            
        </tr> 
    </thead>
    <tfoot>
        {% for items in articles %}
        {% if items.art_publisher == request.user %}
        <tr>
           <td style="width: 300px;">{{items.art_code}} </td> 
           <td style="width: 300px;">{{items.art_title}} </td>
           <td style="width: 300px;">{{items.art_category}} </td>
           <td style="width: 300px;">{{items.art_description}} </td>
           <td style="width: 300px;">{{items.art_volume}} </td> 
           <td style="width: 300px;">{{items.art_date}} </td> 
           <td style="width: 300px;">You </td>
           <td style="width: 300px;">
            <a href="{% url 'edit_art' items.art_code %}" class="button is-info">Edit  &nbsp <i class="fas fa-edit"></i></a></td>
           <td style="width: 300px;"><a href="{% url 'del_art' items.art_code %}" class="button is-danger">Delete  &nbsp<i class="fas fa-trash-alt"></i></a></td>
           {% else %} 
           <td style="width: 300px;">{{items.art_code}} </td> 
           <td style="width: 300px;">{{items.art_title}} </td>
           <td style="width: 300px;">{{items.art_category}} </td>
           <td style="width: 300px;">{{items.art_description}} </td>
           <td style="width: 300px;">{{items.art_volume}} </td> 
           <td style="width: 300px;">{{items.art_date}} </td> 
           <td style="width: 300px;">{{items.art_publisher}} </td> 
           <td style="width: 300px;"><a href="#" class="button is-success">View  &nbsp <i class="fas fa-eye"></i></a></td>
           <td style="width: 300px;"></td>
        {% endif %}

        </tr>
        
      
    {% endfor %}
    </tfoot> 
    </table>
    
</div>
    <!--<p>test this wasn't published by you</p>-->
 


<br><br>
 <div class="columns">
        {% if active_team %}
            <div class="column is-4">
                <div class="notification has-background-success-light">
                    <h3 class="is-size-5">{{ active_team.title }}{% if active_team.created_by == request.user %}(You are the Owner){% else %}(Member){% endif %}</h3>
                
                    <h3 class="is-size-6">You are a Member of this team</h3>

                    <hr>

                    <a href="{% url 'team:team' active_team.id %}" class="button is-success">Details</a>

                    {% if active_team.created_by == request.user %}
                        <a href="{% url 'team:invite' %}" class="button is-info">Invite users</a>
                    {% endif %}
                </div>
            </div>
        {% endif %}

        {% for team in teams %}
            <div class="column is-4">
                <div class="notification">
                    <h3 class="is-size-5">{{ team.title }}{% if team.created_by == request.user %}(Owner){% else %}(Member){% endif %}</h3>
                
                    <h3 class="is-size-6">You are a Member of this team</h3>

                    <hr>

                    <a href="{% url 'team:team' team.id %}" class="button is-success">Details</a>
                    <a href="{% url 'team:activate_team' team.id %}" class="button is-info">Activate</a>
                </div>
            </div>
        {% endfor %}
    </div>
 
{% endblock %}