Invitation/urls.py
from django.conf import settings
from django.conf.urls.static import static

from os import name
from django.contrib import admin
from django.urls import path
from django.contrib.auth import views as auth_views
from django.urls.conf import include

from apps.core.views import frontpage,privacy, terms,plans,code
from apps.userprofile.views import accept_invitation

urlpatterns = [
    path('', frontpage, name='frontpage'),
    path('terms/', terms, name='terms'),
    path('privacy/', privacy, name='privacy'),
    path('plans/', plans, name='plans'),
    path('admin/', admin.site.urls),
    
    #
    #Dashboard
    
      path('myaccount/', include('apps.userprofile.urls')), 
      path('myaccount/teams/', include('apps.team.urls')), 
    #
    #Auth
    
    #path('sign/', include('apps.userprofile.urls')),
    path('signup/', code, name="signup"),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html' ), name="login"),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
  
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/team/urls.py
#import django

from django.conf.urls import url
from django.urls import path

from .views import add, team, edit,activate_team, invite
app_name = 'team'

urlpatterns = [
    path('add/', add, name='add'),
    path('edit/', edit, name='edit'),
    path('invite/', invite, name='invite'),
    path('activate_team/<int:team_id>', activate_team, name='activate_team'),
    path('<int:team_id>/', team, name='team'),
    
]

apps/team/models.py
from Invitation.settings import DEFAULT_AUTO_FIELD
from django.db import models
from django.contrib.auth.models import User
from django.db.models.fields import CharField
# Create your models here.

class Team(models.Model):
    ACTIVE = 'active'
    DELETED = 'deleted'
    
    CHOICES_STATUS = {
        (ACTIVE, 'Active'),
        (DELETED, 'Deleted'),
    }
    
    #
    #
    title = models.CharField(max_length=255)
    members = models.ManyToManyField(User,related_name="teams")
    created_by = models.ForeignKey(User,related_name="created_teams", on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    status = models.CharField( max_length=10, choices=CHOICES_STATUS, default=ACTIVE)
    
    class Meta:
        ordering= ['title']
    
    def __str__(self):
        return self.title
    
class Invite(models.Model):
    #
    # Status
    INVITED = 'Invited'
    ACCEPTED = 'Accepted'

    CHOICES_STATUS = (
        (INVITED, 'Invited'),
        (ACCEPTED, 'Accepted')
    )
    team = models.ForeignKey(Team, related_name="invitations", on_delete=models.CASCADE)
    email= models.EmailField()
    code = models.CharField( max_length=20)
    status = models.CharField( max_length=20, choices=CHOICES_STATUS, default=INVITED)
    date_sent = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.email
    

apps/team/views.py
# Import Django
from django.utils.html import conditional_escape
from apps.userprofile.models import Userprofile
from django.contrib import messages
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib.auth.decorators import login_required
from django.template.loader import render_to_string
# Create your views here.

from .utilities import send_invitation, send_invitation_accepted

from .models import Invite, Team
import random
#
#views




@login_required
def team(request, team_id):
    team = get_object_or_404(Team, pk=team_id, status=Team.ACTIVE, members__in=[request.user])
    invitations= team.invitations.filter(status=Invite.INVITED)
    return render(request, 'team/team.html', {'team': team, 'invitations':invitations})

@login_required
def add(request):
    if request.method == "POST":
        title = request.POST.get('title')
        if title:
            team = Team.objects.create(title=title, created_by=request.user)
            team.members.add(request.user)
            team.save()
            
            userprofile = request.user.userprofile
            userprofile.active_team_id = team.id 
            userprofile.save()
            
            return redirect('myaccount')
    return render(request, 'team/add.html')

@login_required
def edit(request):
    team = get_object_or_404(Team, pk=request.user.userprofile.active_team_id, status=Team.ACTIVE, members__in=[request.user])
    if request.method == "POST":
        title = request.POST.get('title')
        
        if title:
            team.title = title
            team.save()
            
            messages.info(request, 'The Changes Were Saved')
            
            return redirect('team:team', team_id=team.id)
    return render(request, 'team/edit.html', {'team':team})

@login_required
def activate_team(request, team_id):
    team = get_object_or_404(Team, pk=team_id, status=Team.ACTIVE, members__in=[request.user])
    userprofile = request.user.userprofile
    userprofile.active_team_id = team.id
    userprofile.save()
    
    messages.info(request, 'The Team Was Activated')
    
    return redirect('team:team', team_id=team_id)

@login_required
def invite(request):
    team = get_object_or_404(Team, pk=request.user.userprofile.active_team_id, status=Team.ACTIVE, members__in=[request.user])

    if request.method == 'POST':   
        email = request.POST.get('email')
        
        if email:
            invitations= Invite.objects.filter(team=team, email=email)
            
            if not invitations:
                code = ''.join(random.choice('abcdefghijklmnopqrstuvwxyz1234567890') for i in range(6))
                invitation = Invite.objects.create(team=team, email=email, code=code)
                
                messages.info(request, 'The User was Invited')
                
                send_invitation(email, code, team)
                
                return redirect('team:team', team_id=team.id)
            else:
                messages.info(request, 'The User has already been invited')
                
    return render(request, 'team/invite.html', {'team':team})

apps/team/templates/team/add.html
{% extends 'core/base.html' %}

{% block title %}Add team | {% endblock %}

{% block content %}
    <nav class="breadcrumb" aria-label="breadcrumbs">
        <ul>
            <li><a href="#">Dashboard</a></li>
            <li><a href="{% url 'myaccount' %}">My account</a></li>
            <li class="is-active"><a href="{% url 'team:add' %}" aria-current="page">Add team</a></li>
        </ul>
    </nav>

    <div class="columns" id="team-app">
        <div class="column is-4">
            <h1 class="title">Add team</h1>

            <form method="post" action="." @submit="validateForm">
                {% csrf_token %}

                <div class="field">
                    <label>Title</label>

                    <div class="control">
                        <input type="text" class="input" name="title" id="id_title" v-model="title">
                    </div>
                </div>

                <div class="notification is-danger" v-if="errors.length">
                    <p v-for="error in errors">[[ error ]]</p>
                </div>

                <div class="field" >
                    <div class="control" >
                        <button class="button is-success">Submit</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

{% block scripts %}
<script>
    const TeamApp = {
        data() {
            return {
                title: '',
                errors: []
            }
        },
        delimiters: ['[[', ']]'],
        methods: {
            validateForm(e) {
                this.errors = []

                if (this.title) {
                    return true
                }

                e.preventDefault()

                this.errors.push('The title field is missing')
                
                return false
            }
        }
    }

    Vue.createApp(TeamApp).mount('#team-app')
</script>
{% endblock %}

apps/team/templates/team/edit.html
{% extends 'core/base.html' %}

{% block title %}Edit team | {% endblock %}

{% block content %}
    <nav class="breadcrumb" aria-label="breadcrumbs">
        <ul>
            <li><a href="#">Dashboard</a></li>
            <li><a href="{% url 'myaccount' %}">My account</a></li>
            <li class="is-active"><a href="{% url 'team:edit' %}" aria-current="page">Edit team</a></li>
        </ul>
    </nav>

    <div class="columns" id="team-app">
        <div class="column is-4">
            <h1 class="title">Edit team</h1>

            <form method="post" action="." @submit="validateForm">
                {% csrf_token %}

                <div class="field">
                    <label>Title</label>

                    <div class="control">
                        <input type="text" name="title" id="id_title" class="input" v-model="title">
                    </div>
                </div>

                <div class="notification is-danger" v-if="errors.length">
                    <p v-for="error in errors">[[ error ]]</p>
                </div>

                <div class="field">
                    <div class="control">
                        <button class="button is-success">Save Changes</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

{% block scripts %}
<script>
    const TeamApp = {
        data() {
            return {
                title: '{{team.title}}',
                errors: []
            }
        },
        delimiters: ['[[', ']]'],
        methods: {
            validateForm(e) {
                this.errors = []

                if (this.title) {
                    return true
                }

                e.preventDefault()

                this.errors.push('The title field is missing')
                
                return false
            }
        }
    }

    Vue.createApp(TeamApp).mount('#team-app')
</script>
{% endblock %}

apps/team/templates/team/email_invitation.html
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        
        <title>Int Project</title>

        <style type="text/css">
            html {
                width: 100%;
            }

            body {
                width: 100%;
                font-family: Arial;
                font-size: 14px;
                background-color: #fff;
                color: #333;
            }

            a {
                color: #111;
            }
        </style>
    </head>

    <body>
        <table width="100%" cellspacing="0" cellpadding="0">
            <tr>
                <td><h1>Internship Project - Invitation to {{ team.title }}</h1></td>
            </tr>

            <tr>
                <td>
                    <p>You have been invited to join {{ team.title }}</p>
                    <p>Click the link below to sign up or log in. Your team activation code is {{ code }}</p>
                </td>
            </tr>

            <tr>
                <td>
                    <a href="{{ acceptation_url }}">Accept invitation</a>
                </td>
                <td> <br>
                <br> 
                <p>~Yvan Brunel. ESPIN 2021</p>
                </td>
            </tr>
        </table>
    </body>
</html>

apps/team/templates/team/email_invitation_accepted.html
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        
        <title>Int Project</title>

        <style type="text/css">
            html {
                width: 100%;
            }

            body {
                width: 100%;
                font-family: Arial;
                font-size: 14px;
                background-color: #fff;
                color: #333;
            }

            a {
                color: #111;
            }
        </style>
    </head>

    <body>
        <table width="100%" cellspacing="0" cellpadding="0">
            <tr>
                <td><h1>Internship Project - Invitation to {{ team.title }}</h1></td>
            </tr>

            <tr>
                <td>
                    <p> {{invitation.email}} accepted your invitation </p>
                </td>
            </tr>

        
        </table>
    </body>
</html>

apps/team/templates/team/invite.html
{% extends 'core/base.html' %}

{% block title %}Invite Member | {% endblock %}

{% block content %}
    <nav class="breadcrumb" aria-label="breadcrumbs">
        <ul>
            <li><a href="#">Dashboard</a></li>
            <li><a href="{% url 'myaccount' %}">My account</a></li>
            <li><a href="{% url 'team:team' team.id %}" >{{team.title}}</a></li>
            <li class="is-active"><a href="{% url 'team:invite' %}" aria-current="page">Invite Member</a></li>
        </ul>
    </nav>

    <div class="columns is-multiline " id="invite-app">
        <div class="column is-4">
            <h1 class="title">Invite Member</h1>
             <div class="notification is-danger" v-if="errors.length">
                <p v-for="error in errors">[[ error ]]</p>
            </div>

            <form method="post" action="." @submit="validateForm" novalite>
                {% csrf_token %}

                <div class="field">
                    <label>E-mail</label>

                    <div class="control">
                        <input type="email" name="email" id="id_email" v-model="email" class="input">
                    </div>
                </div>

                <div class="field">
                    <div class="control">
                        <button class="button is-success">Send invitation</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

{% block scripts %}
<script>
    const InviteApp = {
        data() {
            return {
                email: '',
                errors: []
            }
        },
        delimiters: ['[[', ']]'],
        methods: {
            validateForm(e) {
                if (this.validateEmail(this.email)) {
                    return true
                }

                this.errors = ['The e-mail is not valid']

                e.preventDefault()

                return false
            },
            validateEmail(email) {
                if (/^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:\.[a-zA-Z0-9-]+)*$/.test(email)) {
                    return true
                }

                return false
            }
        }
    }

    Vue.createApp(InviteApp).mount('#invite-app')
</script>
{% endblock %}

apps/team/templates/team/team.html
{% extends 'core/base.html' %}

{% block title %}{{team.title}} | {% endblock %}

{% block content %}
    <nav class="breadcrumb" aria-label="breadcrumbs">
        <ul>
            <li><a href="#">Dashboard</a></li>
            <li><a href="{% url 'myaccount' %}">My account</a></li>
            <li class="is-active"><a href="{% url 'team:team' team.id %}" aria-current="page">{{team.title}}</a></li>
        </ul>
    </nav>

    <div class="columns is-multiline " id="team-app">
        <div class="column is-4">
            <h1 class="title">{{team.title}}</h1>
        
        {% if request.user == team.created_by %}
                <a href="{% url 'team:invite' %}" class="button is-primary">Invite users</a>
            {% endif %}
       <hr>

            <h2 class="subtitle mt-6">Members</h2>

            {% for member in team.members.all %}
                <p>{{ member.username }}</p>
            {% endfor %}

        <h2 class="subtitle mt-6">Invited Members</h2>
        {% for member in invitations %}
        
        <p><strong>{{member.email}}</strong> - was invited {{member.date_sent|timesince}} ago</p>
        {% endfor %}

        </div>

        {% if team.created_by == request.user %}

                <div class="column is-12">

            <hr>

            <h3 class="subtitle"> Owner Actions</h3>

            <a href="{% url 'team:edit' %}" class="button is-warning">Edit Team</a>
            </div>
        {% endif %}

        <hr>
    </div>
{% endblock %}